SELECT * FROM test.BANKDIRECTORY;

SELECT COUNT(*) FROM test.BANKDIRECTORY;

SELECT * FROM test.BANKDIRECTORY WHERE ISO_COUNTRY_CODE = 'US';

SELECT * FROM test.BANKDIRECTORY WHERE BIC8='ABKKAEAD';

SELECT * FROM test.BANKDIRECTORY WHERE BIC8='BOFAUS3N';

SELECT * FROM test.BANKDIRECTORY WHERE NATIONAL_ID = '011001331';

SELECT * FROM test.BANKDIRECTORY WHERE NATIONAL_ID = '063238';

SELECT * FROM test.BANKDIRECTORY WHERE NATIONAL_ID = '053112479';

SELECT * FROM test.BANKDIRECTORY WHERE RECORD_KEY = 'BD000000DB49';

SELECT * FROM test.BANKDIRECTORY WHERE BIC8 = 'ABNAKZKX' AND  NATIONAL_ID='922';

SELECT * FROM test.BANKDIRECTORY WHERE BIC8 = 'BOFAUS3N' AND  NATIONAL_ID='026009593';


SELECT BIC, BIC8  FROM test.BANKDIRECTORY WHERE RECORD_KEY = 'BD000000SNSN';

SELECT * FROM test.BANKDIRECTORY WHERE BIC8 like '%BKKAEA%';

SELECT BIC, COUNT(*) AS count  FROM test.BANKDIRECTORY GROUP BY BIC HAVING count > 1;

SELECT BIC8, COUNT(*) AS count  FROM test.BANKDIRECTORY GROUP BY BIC8 HAVING count > 1;

SELECT NATIONAL_ID, COUNT(*) AS count  FROM test.BANKDIRECTORY GROUP BY NATIONAL_ID HAVING count > 1;

SELECT BIC8, NATIONAL_ID,  COUNT(*) AS count FROM test.BANKDIRECTORY GROUP BY BIC8, NATIONAL_ID HAVING count > 1;





