SELECT RECORD_KEY, PARENT_OFFICE_KEY, BIC8, NATIONAL_ID FROM test.BANKDIRECTORY WHERE NATIONAL_ID = '075000941';

SELECT RECORD_KEY, PARENT_OFFICE_KEY, BIC8, NATIONAL_ID from test.BANKDIRECTORY WHERE RECORD_KEY =
  ( SELECT PARENT_OFFICE_KEY FROM test.BANKDIRECTORY WHERE NATIONAL_ID = '075000941' );

